(* ::Package:: *)

(* ::Input:: *)
(*#!/usr/local/bin/MathematicaScript -script*)
(**)
(*url = ToExpression[Rest[$ScriptCommandLine]];*)
(*RemoveBackground[*)
(*ColorNegate[*)
(*EdgeDetect[*)
(*Import["/Users/Pradyuman/Documents/LiveTrace/PurdueEngineering.jpg"]]]]*)
